### ISSUE TITLE
No cleaning done in titanic preprocessing

### ISSUE THREAD

**Issue by amosaini** [lsjsj92/kubeflow_example#1]
The main function does have the code to get the data but It does not have the code to preprocess and upload the data to s3.

**Comment by lsjsj92** [comment]
Hi. Is this the code you're looking for?

https://github.com/lsjsj92/kubeflow_example/blob/master/titanic/preprocessing/preprocessing.py#L16

**Comment by amosaini** [comment]
yes this code is not being utilized anywhere.

**Comment by lsjsj92** [comment]
Ah~ in preprocessing step, there is no upload examples were addded in that part.

But, it's added to this part. please check this code
https://github.com/lsjsj92/kubeflow_example/blob/master/titanic/train_model/training.py#L108

if you want to use in preprocess step, just add like that example
